////
Copyright 2024 Tobias Loew
Distributed under the Boost Software License, Version 1.0.
http://www.boost.org/LICENSE_1_0.txt
////

:source-highlighter: rouge
:source-language: cpp

[#design_rationale]
# Design rationale
:toc:
:toc-title: 
:idprefix:
// :stem: latexmath



The design of Boost.Flags was driven by the following principles:

* type-safety
** the library shall enforce that binary operators can only be applied to flags (resp. their complements) from the same enumeration 
** flag values shall be distinguishable from their complements on the type-level

* non-intrusive
** as few as possible changes to the definition of existing flag-like enumeration shall be required
** do not introduce new types when using flags on enumerations, except the `complement` template

* opt-in shall be done by
** by simple macro invocations

* zero-overhead
** for optimized builds operator-calls must produce the same assembly code as built-in calls on the underlying integers

* no change of semantics for existing code
** enabling Boost.Flags for an existing flag-like enumeration must not produce valid code with different semantics 
** erroneous usage of binary operators (e.g. applying operators to different enumerations) shall produce compilation errors

The first four principles are met by the library. The last principle of course has a notable exception: 
 For a given enumeration `E` values of type `complement<E>` may invoke different overloads than values of `E`.

