////
Copyright 2002, 2017 Peter Dimov

Distributed under the Boost Software License, Version 1.0.

See accompanying file LICENSE_1_0.txt or copy at
http://www.boost.org/LICENSE_1_0.txt
////


// [#current_function_macro]
# Reference
:toc:
:toc-title:
:idprefix:

The contents of the library are in namespace boost::flags.

All operators and functions in this library

* are `constexpr` and `noexcept` 
* use attribute `+[[nodiscard]]+` except for assignment operators `&=`, `|=`, `^=` and functions `modify_inplace`, `add_inplace`, `remove_inplace`

Most of the function signatures for operators are written with trailing return type but the leading `auto` is left out for readability.

## Supported language versions

Boost.Flags requires at least C++11.

Concepts are used if available and not disabled using xref:BOOST_FLAGS_HAS_CONCEPTS[`BOOST_FLAGS_HAS_CONCEPTS`].

## Macros to opt-in


### BOOST_FLAGS

For an enumeration `E` at namespace scope use the following variadic macro to enables all operators of Boost.Flags
[source]
----
BOOST_FLAGS(E)
----

resp.

[source]
----
BOOST_FLAGS(E, OPTIONS)
----
where OPTIONS is an optional comma separated list (if OPTIONS is empty the comma after E may be omitted)
containing at most one of each of the following options:

* `BOOST_FLAGS_LOGICAL_AND`            : enables `operator&&` for `E` (see also xref:logical_and[`logical_and`])
* `BOOST_FLAGS_DISABLE_COMPLEMENT`    : disables the usage of `complement<E>` (see also xref:disable_complement[`disable_complement`])
* `BOOST_FLAGS_NO_FORWARDING`       : do not generate forwarding `friend` operators when using BOOST_FLAGS_LOCAL (has no effect for BOOST_FLAGS) (see also xref:Opt-in[Opt-in] and xref:BOOST_FLAGS_FORWARD_OPERATORS[`BOOST_FLAGS_FORWARD_OPERATORS`])


furthermore at most one of the following relational-operator options may be specified:

* `BOOST_FLAGS_STD_REL`                : use operators <, <=, >, >= and <=> which accept two compatible flag-arguments and compare their underlying values (cf. xref:BOOST_FLAGS_SPECIALIZE_STD_LESS[`BOOST_FLAGS_SPECIALIZE_STD_LESS`])
* `BOOST_FLAGS_PARTIAL_ORDER_REL`      : use order induced by flag entailment relation for operators <, <=, >, >= and <=> (cf. xref:BOOST_FLAGS_REL_OPS_PARTIAL_ORDER[`BOOST_FLAGS_REL_OPS_PARTIAL_ORDER`])
* `BOOST_FLAGS_DELETE_REL`             : delete operators <, <=, >, >= and <=> for type E (cf. xref:BOOST_FLAGS_REL_OPS_DELETE[`BOOST_FLAGS_REL_OPS_DELETE`])

If no relational-operator option is specified, the macro defaults to using 'BOOST_FLAGS_STD_REL`.

[NOTE]
====
When errors are encountered using [BOOST_FLAGS(E, ...)] this can have multiple reasons (list is NOT exhaustive):

* the invoked preprocessor is not standard conforming to at least C++11
* misspelling one of the options
* forgetting a comma or specifying a comma too much
* specifying the same options more than once
* specifying more than one relational-operator option
====

`BOOST_FLAGS(E)` imports all operators of Boost.Flags into the current namespace (cf. xref:BOOST_FLAGS_USING_OPERATORS[`BOOST_FLAGS_USING_OPERATORS()`]).


### BOOST_FLAGS_LOCAL

For an enumeration `E` at class scope use the following variadic macro to enables all operators of Boost.Flags
[source]
----
BOOST_FLAGS_LOCAL(E)
----

resp.

[source]
----
BOOST_FLAGS_LOCAL(E, OPTIONS)
----
enables all operators of Boost.Flags. +
For the description of `OPTIONS` please refer to xref:BOOST_FLAGS[BOOST_FLAGS]+
`BOOST_FLAGS_ENABLE_LOCAL(E)` creates friend functions for all operators of Boost.Flags for the enumeration `E` (cf. xref:BOOST_FLAGS_FORWARD_OPERATORS_LOCAL[BOOST_FLAGS_FORWARD_OPERATORS_LOCAL(E)]).


### Non-variadic macros for enabling

The following macros are primarily provided for non standard conforming preprocessors.

#### BOOST_FLAGS_ENABLE

For an enumeration `E` at namespace scope the macro 
[source]
----
BOOST_FLAGS_ENABLE(E)
----
enables all operators of Boost.Flags. +
`BOOST_FLAGS_ENABLE(E)` imports all operators of Boost.Flags into the current namespace (cf. xref:BOOST_FLAGS_USING_OPERATORS[BOOST_FLAGS_USING_OPERATORS()]).

#### BOOST_FLAGS_ENABLE_DISABLE_COMPLEMENT

For an enumeration `E` at namespace scope the macro 
[source]
----
BOOST_FLAGS_ENABLE_DISABLE_COMPLEMENT(E)
----
enables all operators of Boost.Flags and disables the usage of `complement<E>` (see also xref:disable_complement[`disable_complement`]) +
`BOOST_FLAGS_ENABLE_DISABLE_COMPLEMENT(E)` imports all operators of Boost.Flags into the current namespace (cf. xref:BOOST_FLAGS_USING_OPERATORS[BOOST_FLAGS_USING_OPERATORS()]).


#### BOOST_FLAGS_ENABLE_LOGICAL_AND

For an enumeration `E` at namespace scope the macro 
[source]
----
BOOST_FLAGS_ENABLE_LOGICAL_AND(E)
----
enables all operators of Boost.Flags and enables `operator&&` for `E` (see also xref:logical_and[`logical_and`]) +
`BOOST_FLAGS_ENABLE_LOGICAL_AND(E)` imports all operators of Boost.Flags into the current namespace (cf. xref:BOOST_FLAGS_USING_OPERATORS[BOOST_FLAGS_USING_OPERATORS()]).



#### BOOST_FLAGS_ENABLE_DISABLE_COMPLEMENT_LOGICAL_AND

For an enumeration `E` at namespace scope the macro 
[source]
----
BOOST_FLAGS_ENABLE_DISABLE_COMPLEMENT_LOGICAL_AND(E)
----
enables all operators of Boost.Flags,disables the usage of `complement<E>` (see also xref:disable_complement[`disable_complement`]) and enables `operator&&` for `E` (see also xref:logical_and[`logical_and`]) +
`BOOST_FLAGS_ENABLE_DISABLE_COMPLEMENT_LOGICAL_AND(E)` imports all operators of Boost.Flags into the current namespace (cf. xref:BOOST_FLAGS_USING_OPERATORS[BOOST_FLAGS_USING_OPERATORS()]).





#### BOOST_FLAGS_ENABLE_LOCAL

For an enumeration `E` at class scope the macro 
[source]
----
BOOST_FLAGS_ENABLE_LOCAL(E)
----
enables all operators of Boost.Flags. +
`BOOST_FLAGS_ENABLE_LOCAL(E)` creates friend functions for all operators of Boost.Flags for the enumeration `E` (cf. xref:BOOST_FLAGS_FORWARD_OPERATORS_LOCAL[BOOST_FLAGS_FORWARD_OPERATORS_LOCAL(E)]).


#### BOOST_FLAGS_ENABLE_DISABLE_COMPLEMENT

For an enumeration `E` at class scope the macro 
[source]
----
BOOST_FLAGS_ENABLE_LOCAL_DISABLE_COMPLEMENT(E)
----
enables all operators of Boost.Flags and disables the usage of `complement<E>` (see also xref:disable_complement[`disable_complement`]) +
`BOOST_FLAGS_ENABLE_LOCAL_DISABLE_COMPLEMENT(E)` imports all operators of Boost.Flags into the current namespace (cf. xref:BOOST_FLAGS_USING_OPERATORS[BOOST_FLAGS_USING_OPERATORS()]).


#### BOOST_FLAGS_ENABLE_LOCAL_LOGICAL_AND

For an enumeration `E` at class scope the macro 
[source]
----
BOOST_FLAGS_ENABLE_LOCAL_LOGICAL_AND(E)
----
enables all operators of Boost.Flags and enables `operator&&` for `E` (see also xref:logical_and[`logical_and`]) +
`BOOST_FLAGS_ENABLE_LOCAL_LOGICAL_AND(E)` imports all operators of Boost.Flags into the current namespace (cf. xref:BOOST_FLAGS_USING_OPERATORS[BOOST_FLAGS_USING_OPERATORS()]).



#### BOOST_FLAGS_ENABLE_LOCAL_DISABLE_COMPLEMENT_LOGICAL_AND

For an enumeration `E` at class scope the macro 
[source]
----
BOOST_FLAGS_ENABLE_LOCAL_DISABLE_COMPLEMENT_LOGICAL_AND(E)
----
enables all operators of Boost.Flags,disables the usage of `complement<E>` (see also xref:disable_complement[`disable_complement`]) and enables `operator&&` for `E` (see also xref:logical_and[`logical_and`]) +
`BOOST_FLAGS_ENABLE_LOCAL_DISABLE_COMPLEMENT_LOGICAL_AND(E)` imports all operators of Boost.Flags into the current namespace (cf. xref:BOOST_FLAGS_USING_OPERATORS[BOOST_FLAGS_USING_OPERATORS()]).



## Enabling helper functions, types and macros

[NOTE]
====
The functions, types and macros in this section are usually not used directly, but implicitly through one of the `BOOST_FLAGS...` macros.
====

### BOOST_FLAGS_USING_OPERATORS

The macro `BOOST_FLAGS_USING_OPERATORS()` imports all operators from `namespace boost::flags` into the current namespace. +
This will enable https://en.cppreference.com/w/cpp/language/adl[ADL,window=_blank] for Boost.Flags operators for enumerations in the current namespace. 


### BOOST_FLAGS_USING_UTILITIES

The macro `BOOST_FLAGS_USING_UTILITIES()` imports all utility functions from `namespace boost::flags` into the current namespace. +
This will enable https://en.cppreference.com/w/cpp/language/adl[ADL,window=_blank] for Boost.Flags utility functions for enumerations in the current namespace. 

[NOTE]
====
To import the utility functions into the current namespace the macro `BOOST_FLAGS_USING_UTILITIES()` must be used explicitly. +
There is no `BOOST_FLAGS_ENABLE...` macro that entails `BOOST_FLAGS_USING_UTILITIES()`.
====

### BOOST_FLAGS_USING_ALL

The macro `BOOST_FLAGS_USING_ALL()` is a shorthand for
[source]
----
BOOST_FLAGS_USING_OPERATORS()
BOOST_FLAGS_USING_UTILITIES()
----
(cf. xref:BOOST_FLAGS_USING_OPERATORS[BOOST_FLAGS_USING_OPERATORS], xref:BOOST_FLAGS_USING_UTILITIES[BOOST_FLAGS_USING_UTILITIES])


### BOOST_FLAGS_FORWARD_OPERATORS

For an enumeration `E` the macro `BOOST_FLAGS_FORWARD_OPERATORS(E)` creates forwarding functions for all Boost.Flags operators for the enumeration `E` in the current namespace.
Instead of `BOOST_FLAGS_ENABLE(E)`, the sequence
[source]
----
constexpr bool boost_flags_enable(E) { return true; }
BOOST_FLAGS_FORWARD_OPERATORS(E)
----
can be used, which creates forwarding functions instead of importing the operators.


### BOOST_FLAGS_FORWARD_OPERATORS_LOCAL

For an enumeration `E` the macro `BOOST_FLAGS_FORWARD_OPERATORS_LOCAL(E)` creates forwarding friend functions for all Boost.Flags operators for the enumeration `E` in the current class / class template.

[NOTE]
====
Since the language does not allow `using` declarations at class scope, Boost.Flags uses `BOOST_FLAGS_FORWARD_OPERATORS_LOCAL` to ensure that all operators can be found through https://en.cppreference.com/w/cpp/language/adl[ADL,window=_blank].
====




### boost_flags_enable


The function `boost_flags_enable` can be overloaded for an enumeration `E` either 

* with return-type `std::integral_constant<bool, true>`:
+
[source]
----
constexpr std::integral_constant<bool, true> boost_flags_enable(E) { return {}; }
----
enables Boost.Flags for an enumeration `E`. All optional features are disabled.

* or with return-type `boost::flags::options_constant<__options-value__>`:
The flag-enumeration `boost::flags::options` has the options
** `enable`:  enables `E`
** `disable_complement`:  disables the usage of `complement<E>` (see also xref:disable_complement[`disable_complement`])
** `logical_and`:  enables `operator&&` for `E` (see also xref:logical_and[`logical_and`])
e.g.
+
[source]
----
constexpr boost::flags::options_constant<
        boost::flags::options::enable            // enable E (required)
        | boost::flags::options::disable_complement // disable the usage of the complement
        | boost::flags::options::logical_and        // enable operator&&
    > 
        boost_flags_enable(E) { return {}; }
----

The function `boost_flags_enable` is looked up using https://en.cppreference.com/w/cpp/language/adl[ADL,window=_blank].

In case `E` is defined inside a class, a `friend` function can be used for enabling. E.g.

[source]
----
class my_class {
    // ...
    enum class E:unsigned int { ... };
    friend constexpr bool boost_flags_enable(E) { return true; }
    // ...
};
----

A Boost.Flags enabled (scoped/unscoped) enumeration will also be called _(scoped/unscoped) flags_.

Alternatively to using `boost_flags_enable`, the class template xref:types_enable
[`boost::flags::enable`] can be specialized.


// ### boost_flags_disable_complement
// 
// To disable the usage of the `complement` template (cf. xref:negation_operation[`operator~`]) for an enabled enumeration `E`, the function `boost_flags_disable_complement` / has /to be overloaded for `E` with:
// [source]
// ----
// constexpr bool boost_flags_disable_complement(E) { return true; }
// ----
// 
// `boost_flags_disable_complement` is looked up using https://en.cppreference.com/w/cpp/language/adl[ADL,window=_blank].
// 
// In case `E` is defined inside a class, a `friend` function can be used for enabling:
// 
// [source]
// ----
// class my_class {
//     // ...
//     enum class E:unsigned int { ... };
//     friend constexpr bool boost_flags_enable(E) { return true; }
//     friend constexpr bool boost_flags_disable_complement(E) { return true; }
//     // ...
// };
// ----
// 
// Please note, that defining `constexpr bool boost_flags_disable_complement(E) { return true; }` does not enable `E` for Boost.Flags. The definition of `constexpr bool // boost_flags_enable(E) { return true; }` (or equivalent) is still required. 
// 
// (See also xref:disable_complement[`disable_complement`].)
// 
// 
// ### boost_flags_logical_and
// 
// The function
// [source]
// ----
// constexpr bool boost_flags_disable_complement(E) { return true; }
// ----
// enables `operator&&` for `E` with the following semantics
// 
// [source]
// ----
// constexpt operator&&(e1, e2) -> bool { return !!(e1 & e2); }
// ----
// 
// `boost_flags_logical_and` is looked up using https://en.cppreference.com/w/cpp/language/adl[ADL,window=_blank].
// 
// In case `E` is defined inside a class, a `friend` function can be used for enabling:
// 
// [source]
// ----
// class my_class {
//     // ...
//     enum class E:unsigned int { ... };
//     friend constexpr bool boost_flags_enable(E) { return true; }
//     friend constexpr bool boost_flags_logical_and(E) { return true; }
//     // ...
// };
// ----
// 
// Please note, that defining `constexpr bool boost_flags_logical_and(E) { return true; }` does not enable `E` for Boost.Flags. The definition of `constexpr bool // boost_flags_enable(E) { return true; }` (or equivalent) is still required. 
// 
// (See also xref:logical_and[`logical_and`].)

### enable<T>
[#types_enable]

To enable the Boost.Flags functionality specialize the template for an enumeration 

[source]
----
template<typename T> struct enable : std::false_type {};
----

and inherit from `std::true_type`.

Example:
[source]
----
enum class my_flags : unsigned int {
    option_a = 0x1,
    option_b = 0x2,
};

template<> struct boost::flags::enable<my_flags> : std::true_type {};
----

A Boost.Flags enabled (scoped/unscoped) enumeration will also be called _(scoped/unscoped) flags_.

When `boost::flags::enable` is specialized for `E` any definition of `boost_flags_enable` for `E` are ignored
(cf. xref:boost_flags_enable[`boost_flags_enable`]).


[#disable_complement]
### disable_complement

If the specialization of `enable` additionally inherits from `disable_complement` then the usage of the `complement` template (cf. xref:negation_operation[`operator~`]) is disabled.

When `disable_complement` is used, then the used enumeration must either be scoped, or has an explicit specified underlying type, otherwise the `operator~` may invoke undefined behaviour. For more information, see the following note.

Example:
[source]
----
template<> struct boost::flags::enable<E> 
    : std::true_type
    , boost::flags::disable_complement 
    {};
----

(cf. xref:BOOST_FLAGS_ENABLE_DISABLE_COMPLEMENT[`BOOST_FLAGS_ENABLE_DISABLE_COMPLEMENT`])

[NOTE]
====
For unscoped enumerations with unspecified underlying type, the compiler infers two types:

* the underlying type (https://eel.is/c++draft/dcl.enum#7[,window=_blank]), which we can query using `std::underlying_type`
* a hypothetical integer value type with minimal width such that all enumerators can be represented (https://eel.is/c++draft/dcl.enum#8[,window=_blank]) +
  "The width of the smallest bit-field large enough to hold all the values of the enumeration type [...]." 
  
//  This type is not deducible from the type of the enumeration. (It requires to know the values of all enumerators.)

The legal values for the enumeration are those of the hypothetical integer value type.

But, this hypothetical integer value type is not deducible from the type of the enumeration. (It requires to know the values of all enumerators.) Furthermore, it is in general not the same as the underlying type. E.g.
[source]
----
enum TriBool {
    false_ = 0,
    true_ = 1,
    undefined = 2
};
----
has underlying type `int` on all major compilers, but its valid values are just 
`0`, `1`, `2` and `3` as the __hypothetical integer value type with minimal width__ is a 2-bit unsigned integer.

====

[#logical_and]
### logical_and

If the specialization of `enable` additionally inherits from `logical_and` then `operator&&` is enabled.

Example:
[source]
----
template<> struct boost::flags::enable<E> 
    : std::true_type
    , boost::flags::logical_and 
    {};
----

(cf. xref:BOOST_FLAGS_ENABLE_LOGICAL_AND[`BOOST_FLAGS_ENABLE_LOGICAL_AND`])



## Types


[#complement]
### complement<T>

The template `complement` indicates that a value is the bitwise negation of a flag-value.
It is used to distinguish flag-values from _negative masks_.

[source]
----
template<typename T> struct complement; 
----

By default the usage of `complement` is enabled but can be disabled using xref:disable_complement[`disable_complement`]. 

// Boost.Flags operators and functions will always strip double `complement`s from flags.







### total_order_t

The type `boost::flags::total_order_t` defines a call-operator which accepts two compatible flag-arguments and compares their underlying values.
(cf. xref:BOOST_FLAGS_SPECIALIZE_STD_LESS[BOOST_FLAGS_SPECIALIZE_STD_LESS]).

There is also a functions object

`static constexpr boost::flags::total_order_t total_order;`



### partial_order_t

The type `boost::flags::partial_order_t` defines a call-operator which accepts two compatible flag-arguments and compares them based on flag entailment.
(cf. xref:BOOST_FLAGS_REL_OPS_PARTIAL_ORDER[BOOST_FLAGS_REL_OPS_PARTIAL_ORDER]).

There is also a functions object

`static constexpr boost::flags::partial_order_t partial_order;`



## Operators

[#negation_operation]
### operator~

Reverses all bits of the underlying integer representation of its argument.

The signature of `operator~` depends on whether `complement` is enabled (cf. xref:disable_complement[disable_complement]).

When `complement` is enabled for flags `E`

* `operator~(E) \-> complement<E>`
* `operator~(complement<E>) \-> E`

otherwise

* `operator~(E) \-> E`




### operator&

Applies a bitwise AND operation on the underlying integer representations of its arguments.

The signature of `operator&` depends on whether `complement` is enabled (cf. xref:disable_complement[disable_complement]).

When `complement` is enabled for flags `E`

* `operator&(E, E) \-> E`
* `operator&(complement<E>, E) \-> E`
* `operator&(E, complement<E>) \-> E`
* `operator&(complement<E>, complement<E>) \-> complement<E>`

otherwise

* `operator&(E, E) \-> E`

All other `operator&` where at least one of the arguments is enabled and both are implicitly convertible to an integer type are deleted.


### operator|

Applies a bitwise AND operation on the underlying integer representations of its arguments.

The signature of `operator|` depends on whether `complement` is enabled (cf. xref:disable_complement[disable_complement]).

When `complement` is enabled for flags `E`

* `operator|(E, E) \-> E`
* `operator|(complement<E>, E) \-> complement<E>`
* `operator|(E, complement<E>) \-> complement<E>`
* `operator|(complement<E>, complement<E>) \-> complement<E>`

otherwise

* `operator|(E, E) \-> E`

All other `operator|` where at least one of the arguments is enabled and both are implicitly convertible to an integer type are deleted.



### operator^

Applies a bitwise XOR operation on the underlying integer representations of its arguments.

The signature of `operator^` depends on whether `complement` is enabled (cf. xref:disable_complement[disable_complement]).

When `complement` is enabled for flags `E`

* `operator^(E, E) \-> E`
* `operator^(complement<E>, E) \-> complement<E>`
* `operator^(E, complement<E>) \-> complement<E>`
* `operator^(complement<E>, complement<E>) \-> E`

otherwise

* `operator^(E, E) \-> E`

All other `operator^` where at least one of the arguments is enabled and both are implicitly convertible to an integer type are deleted.


### operator&=

Performs a bitwise AND assignment on the underlying integer representations of its arguments.

The signature of `operator&=` depends on whether `complement` is enabled (cf. xref:disable_complement[disable_complement]).

When `complement` is enabled for flags `E`

* `operator&=(E&, E) \-> E&`
* `operator&=(E&, complement<E>) \-> E&`
* `operator&=(complement<E>&, complement<E>) \-> complement<E>&`

[NOTE]
====
The assignment `operator&=(complement<E>&, E)` is *not* available, as it would change the type of the first argument.
====

otherwise

* `operator&=(E&, E) \-> E&`




### operator|=

Performs a bitwise OR assignment on the underlying integer representations of its arguments.

The signature of `operator|=` depends on whether `complement` is enabled (cf. xref:disable_complement[disable_complement]).

When `complement` is enabled for flags `E`

* `operator|=(E&,E) \-> E&`
* `operator|=(complement<E>&,E) \-> complement<E>&`
* `operator|=(complement<E>&,complement<E>) \-> complement<E>&`

[NOTE]
====
The assignment `operator|=(E&, complement<E>)` is *not* available, as it would change the type of the first argument.
====

otherwise

* `operator|=(E&,E) \-> E&`




### operator^=

Performs a bitwise XOR assignment on the underlying integer representations of its arguments.

The signature of `operator^=` depends on whether `complement` is enabled (cf. xref:disable_complement[disable_complement]).

When `complement` is enabled for flags `E`

* `operator^=(E&,E) \-> E&`
* `operator^=(complement<E>&,E) \-> complement<E>&`

[NOTE]
====
The assignment `operator^=(E&, complement<E>)` and `operator^=(complement<E>&, complement<E>)` are *not* available, as they would change the type of the first argument.
====

otherwise

* `operator^=(E&,E) \-> E&`



### operator!

Tests if a value is empty.

[source]
----
    // pseudo code
    [[nodiscard]] constexpr bool operator!(E e) noexcept { return e == E{}; }
----


### Pseudo operator BOOST_FLAGS_AND

Takes the bitwise AND of its arguments and converts the result to `bool`.

[source]
----
    // pseudo code
    [[nodiscard]] constexpr bool operator BOOST_FLAGS_AND(E e1, E e2) noexcept { return !!(e1 & e2); }
----

`BOOST_FLAGS_AND` has same precedence and associativity as `operator&`. It is a macro defined as +

[source]
----
#define BOOST_FLAGS_AND  & boost::flags::impl::pseudo_and_op_tag{} &
----


## operator== , operator!=

The description is only given for `operator==`. Calls with reversed arguments and to `operator!=` will constructed by rewrite rules.

* `operator==(E, E) \-> bool`
* `operator==(complement<E>, complement<E>) \-> bool` 

equality is defined as usual by applying the operator to the underlying integer.

Furthermore the following overloads are defined

* `operator==(E, std::nullptr_t) \-> bool`
* `operator==(E, boost::flags::null_tag) \-> bool`

Both test for equality with an underlying value of `0`. The macro xref:BOOST_FLAGS_NULL[`BOOST_FLAGS_NULL`] defines an instance of `boost::flags::null_tag`.

All other `operator==` and `operator!=` where at least one of the arguments is enabled and both are implicitly convertible to an integer type are deleted.


[NOTE]
====
If `E` is a scoped enumeration then
[source]
----
    bool foo(E e){
        return e == 0;  // literal 0 converts to nullptr, thus
                        // operator==(E, std::nullptr_t) will be called
    }
----
compiles and returns the expected result.

when `E` is unscoped then above code will fail to compile: the overload `operator(E, int)` is deleted for unscoped enumerations. +
If it wasn't then comparison with arbitrary integer values would be possible, as unscoped enumerations implicitly convert to their underlying integer type.


====


## Relational operators <, \<=, > and >=
The relational operators for enumerations (scoped and unscoped) are provided by the language (by applying the resp. operator to the underlying value).
Furthermore, the current wording doesn't allow overloading or deleting those operators by a templated operator (there is a pending Defect Report on this topic: 
https://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2730[,window=_blank]).

There are macros xref:BOOST_FLAGS_REL_OPS_PARTIAL_ORDER[BOOST_FLAGS_REL_OPS_PARTIAL_ORDER] to overload and xref:BOOST_FLAGS_REL_OPS_DELETE[BOOST_FLAGS_REL_OPS_DELETE] to delete relational operators.

[WARNING]
====
It is recommended to define either `BOOST_FLAGS_REL_OPS_DELETE` for flag-like enumerations.

This prohibits the accidental usage of relational operators with flag values ( 
The built-in semantics for relational operators compare the underlying numerical values and do not coincide with flag entailment!).

When flags have to be stored in ordered container or sorted, please either define `BOOST_FLAGS_SPECIALIZE_STD_LESS(E)` for the enumeration or specify `boost::flags::total_order_t` as _Compare_ predicate type.

Range algorithms require the specification of `boost::flags::total_order` as compare object.

====

## Boolean predicates

### any
Tests if a value is not empty.

[source]
----
    // pseudo code
    [[nodiscard]] constexpr bool any(E e) noexcept { return e != E{}; }
----



### none
Tests if a value is empty.

[source]
----
    // pseudo code
    [[nodiscard]] constexpr bool none(E e) noexcept { return e == E{}; }
----



### intersect
Tests if two values have common bits set.

[source]
----
    // pseudo code
    [[nodiscard]] constexpr bool intersect(E e1, E e2) noexcept { return e1 & e2 != E{}; }
----


### disjoint
Tests if two values do not have a common bit set.

[source]
----
    // pseudo code
    [[nodiscard]] constexpr bool disjoint(E e1, E e2) noexcept { return e1 & e2 == E{}; }
----


### subseteq
Tests if all bits set in the first argument are also set in the second argument.

[source]
----
    // pseudo code
    [[nodiscard]] constexpr bool subseteq(E e1, E e2) noexcept { return e1 & e2 == e1; }
----


### subset
Tests if the bits set in the first argument are a proper subset of the bits in the second argument.

[source]
----
    // pseudo code
    [[nodiscard]] constexpr bool subset(E e1, E e2) noexcept { return subseteq(e1, e2) && (e1 != e2); }
----





## Utility functions


### make_null

[source]
----
    // pseudo code
    [[nodiscard]] constexpr E make_null(E) noexcept { return E{}; }
----

For flags `E` returns an _empty_ instance of type `E`, i.e. with underlying value of `0`.  





### make_if

[source]
----
    // pseudo code
    [[nodiscard]] constexpr E make_if(E e, bool set) noexcept { return set ? e : E{}; }
----

Depending on `set` returns either the first argument or empty an instance of type `E`.






### modify

[source]
----
    // pseudo code
    [[nodiscard]] constexpr E modify(E e, E mod, bool set) noexcept { return set ? e | mod : e & ~mod; }
----

Depending on `set` either adds or removes all bits from `mod` to `e` and returns the result.






### modify_inplace

[source]
----
    // pseudo code
    constexpr E& modify(E& e, E mod, bool set) noexcept { e = modify(e, mod, set); return e; }
----

Similar to `modify` but applies the modification to `e` and returns it as reference.




### add_if

[source]
----
    // pseudo code
    [[nodiscard]] constexpr E add_if(E e, E mod, bool add) noexcept { return add ? e | mod : e; }
----

Depending on `add` either adds all bits from `mod` to `e` or leaves `e` unmodified and returns the result.






### add_if_inplace

[source]
----
    // pseudo code
    constexpr E& add_if(E& e, E mod, bool add) noexcept { e = add_if(e, mod, add); return e; }
----

Similar to `add_if` but applies the modification to `e` and returns it as reference.



### remove_if

[source]
----
    // pseudo code
    [[nodiscard]] constexpr E remove_if(E e, E mod, bool remove) noexcept { return remove ? e & ~mod : e; }
----

Depending on `remove` either removes all bits from `mod` from `e` or leaves `e` unmodified and returns the result.






### remove_if_inplace

[source]
----
    // pseudo code
    constexpr E& remove_if(E& e, E mod, bool remove) noexcept { e = remove_if(e, mod, remove); return e; }
----

Similar to `remove_if` but applies the modification to `e` and returns it as reference.





### get_underlying
Returns the underlying value. +
Let `U` be the underlying type of enabled enum `E`
[source]
----
    // pseudo code
    constexpr U get_underlying(E e) noexcept { return static_cast<U>(e); }
----

### from_underlying
Casts an value from underlying value the an enabled enum. +
Let `U` be the underlying type of enabled enum `E`
[source]
----
    // pseudo code
    constexpr E from_underlying(U u) noexcept { return static_cast<E>(u); }
----


### nth_bit

[source]
----
    // pseudo code
    template<typename T = int> 
    [[nodiscard]] constexpr underlying_or_identity<T>::type nth_bit(unsigned int n) noexcept { 
        return static_cast<underlying_or_identity<T>::type>(1) << n; 
    }
----

Returns a value of type `T` with the n-th bit from the right set (zero-based) set.
The type `T` can be either an enumeration or an integral type, and `underlying_or_identity` is a type-trait returning the underlying type of the enumeration or it is the type-identity respectively.


### next_bit

[source]
----
    // pseudo code
    template<typename T> 
    [[nodiscard]] constexpr T next_bit(T v) { return v << 1; }
----

Returns to a value `v` of type `T` the value with the next higher bit set (if available). +
The behaviour is undefined if more than one bit is set in value `v`.



## Flags generator

### flag_generator

The `template<typename E> flag_generator` provides an internal iterator and member functions `begin()` and `end()` returning the resp. iterators. +
It is contructed with the lowest and highest flag that shall be iterated over.
If `flag_generator` is constructor with flags not having exactly one bit set, then the behaviour is undefined.

### flags_from_to
The function
[source]
----
    template<typename E> 
    [[nodiscard]] constexpr flag_generator<E> flags_from_to(E first, E last);
----
returns a `flag_generator` instance iterating from `first` to `last` (incl.).
    
### flags_to
The function
[source]
----
    template<typename E> 
    [[nodiscard]] constexpr flag_generator<E> flags_to(E last);
----
returns a `flag_generator` instance iterating from `E(1)` to `last` (incl.).
    
### flags_all
The function
[source]
----
    template<typename E> 
    [[nodiscard]] constexpr flag_generator<E> flags_all();
----
returns a `flag_generator` instance iterating from `E(1)` to the most significant bit of the underlying type of `E` (incl.), i.e. all bits of the underlying type.
    


## Macros

### BOOST_FLAGS_NULL

The macro `BOOST_FLAGS_NULL` can be used for (in-)equailty testing with a flag-value.

For any value `e` of type flags `E` the expression `e == BOOST_FLAGS_NULL` is equivalent to `e == E{}`. Similarly for  `e != BOOST_FLAGS_NULL`, `BOOST_FLAGS_NULL == e` and `BOOST_FLAGS_NULL != e`.


### BOOST_FLAGS_REL_OPS_DELETE

The macro `BOOST_FLAGS_REL_OPS_DELETE(E)` deletes all relational operators for a Boost.Flags enabled enumeration `E`.

The macro `BOOST_FLAGS_REL_OPS_DELETE(E)` has to be defined at global namespace.



### BOOST_FLAGS_SPECIALIZE_STD_LESS

The macro `BOOST_FLAGS_SPECIALIZE_STD_LESS(E)` specialize std::less for E and complement<E> with the total order based on the value of the underlying integer type (i.e. `<` on the underlying integer type).

The macro `BOOST_FLAGS_SPECIALIZE_STD_LESS(E)` has to be defined at global namespace.

[INFO]
====
The definition of `BOOST_FLAGS_SPECIALIZE_STD_LESS(E)` will not enablerange algorithms to use that total order. Here it is required to explicitely specify `boost::flags::total_order` as compare object.
====


### BOOST_FLAGS_REL_OPS_PARTIAL_ORDER

The macro `BOOST_FLAGS_REL_OPS_PARTIAL_ORDER(E)` defines all relational operators for a Boost.Flags enabled enumeration `E`. +
The following semantics apply

* `e1 \<= e2` : equivalent to `contained(e1, e2)`
* `e1 >= e2` : equivalent to `contained(e2, e1)`
* `e1 < e2` : equivalent to `(contained(e1, e2) && e1 != e2)`
* `e1 > e2` : equivalent to `(contained(e2, e1) && e1 != e2)`
* `e1 \<\=> e2` : has type `std::partial_ordering` and is equivalent to
[source]
----
    e1 == e2
    ? std::partial_ordering::equivalent
    : contained(e1, e2)
    ? std::partial_ordering::less
    : contained(e2, e1)
    ? std::partial_ordering::greater
    : std::partial_ordering::unordered
----


The macro `BOOST_FLAGS_REL_OPS_PARTIAL_ORDER(E)` has to be defined at global namespace.






### BOOST_FLAGS_SPECIALIZE_STD_LESS

The macro `BOOST_FLAGS_SPECIALIZE_STD_LESS(E)` specializes `std::less` for `E` to use `boost::flags::total_order`.


The macro `BOOST_FLAGS_SPECIALIZE_STD_LESS(E)` has to be defined at global namespace.

## Configuration Macros

If not specified, all the following macros are deduced from the system, compiler, C++ version.
(Boost.Flags is tested with all major compilers on linux (ubuntu), macos and windows.)


### BOOST_FLAGS_HAS_THREE_WAY_COMPARISON

Specifies, if three way comparison (<\=>) is available.

Possible values: 0 or 1

### BOOST_FLAGS_HAS_PARTIAL_ORDERING

Specifies, if `std::partial_ordering` is available.

Possible values: 0 or 1


### BOOST_FLAGS_HAS_CONCEPTS

Specifies, if the compiler supports concepts.

Possible values: 0 or 1


### BOOST_FLAGS_HAS_IS_SCOPED_ENUM

Specifies, if `std::is_scoped_enum` is available.

Possible values: 0 or 1



### BOOST_FLAGS_HAS_LOGICAL_TRAITS

Specifies, if the logical traits `std::conjunction`, `std::disjunction` and `std::negation` are available.

Possible values: 0 or 1

### BOOST_FLAGS_HAS_INLINE_VARIABLES

Specifies, if the `inline` variables are available (and work correctly: broken in msvc before version v142).

Possible values: 0 or 1

### BOOST_FLAGS_DEFINE_PARTIAL_ORDERING_OBJECTS

Specifies, if the partial_ordering emulation is defined. +
Only used, when `std::partial_ordering` is not available.

Possible values: 0 or 1


### BOOST_FLAGS_HAS_REWRITTEN_CANDIDATES

Specifies, if https://en.cppreference.com/w/cpp/language/operators[rewitten candidates,window=_blank] are availabe.

Possible values: 0 or 1


### BOOST_FLAGS_WEAK_SYMBOL

Text used to specify a symbol with weak linkage 

* `__declspec(selectany)` for mscv and clang-cl, ICC on windows
* `\\__attribute__\((weak))` for g++ and clang, except for g++ on mingw: in that case please define `BOOST_FLAGS_DEFINE_PARTIAL_ORDERING_OBJECTS=1` in exactly one translation unit



### BOOST_FLAGS_ATTRIBUTE_NODISCARD

Text used as nodiscard attribute (e.g. `\[[nodiscard]]`).

### BOOST_FLAGS_ATTRIBUTE_NODISCARD_CTOR

Text used as nodiscard attribute for constructors (e.g. `\[[nodiscard]]`).

